name: Weekly Forecast

on:
  schedule:
    - cron: '0 22 * * 5'  # UTC 22:00 = 美东时间 17:00 (冬令时)
  workflow_dispatch:      # 手动触发按钮

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install prophet gspread oauth2client google-api-python-client pandas
      - env:
          SERVICE_JSON: ${{ secrets.SERVICE_JSON }}
        run: |
          echo "$SERVICE_JSON" > service.json
          python forecast.py
